### ISSUE TITLE
visualization 'KeyError'

### ISSUE THREAD

**Issue by simremy** [metgem/metgem#103]
Hi Nicolas, 

Working on 10ffc1d I've got this error when I try to launch MDS (same for all the extra visualization)

Thanks for your help

Simon
```

Traceback (most recent call last):
  File "C:\Users\Simon\Documents\GitHub\metgem\metgem_app\workers\options.py", line 16, in __getattr__
    return self.__getitem__(item)
KeyError: 'mds'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Simon\Documents\GitHub\metgem\metgem_app\ui\main_window.py", line 1766, in add_view
    self._workers.start()
  File "C:\Users\Simon\Documents\GitHub\metgem\metgem_app\workers\core\queue.py", line 111, in start
    self.run()
  File "C:\Users\Simon\Documents\GitHub\metgem\metgem_app\workers\core\queue.py", line 123, in run
    worker = item(last_worker)
  File "C:\Users\Simon\Documents\GitHub\metgem\metgem_app\ui\main_window.py", line 1764, in <lambda>
    self._workers.append(lambda _: widget.create_draw_worker())
  File "C:\Users\Simon\Documents\GitHub\metgem\metgem_app\ui\widgets\network.py", line 208, in create_draw_worker
    return [self.create_worker(), process_finished]
  File "C:\Users\Simon\Documents\GitHub\metgem\metgem_app\ui\widgets\network.py", line 310, in create_worker
    return self.worker_class(self._network.scores, self._network.options.mds)
  File "C:\Users\Simon\Documents\GitHub\metgem\metgem_app\workers\options.py", line 18, in __getattr__
    raise AttributeError(e)
AttributeError: 'mds'
```

**Comment by n-elie** [comment]
Thanks for the report
This is fixed in b1c1509
