### ISSUE TITLE
Database search is down, after manual import of some databases

### ISSUE THREAD

**Issue by frperreau** [metgem/metgem#106]
Hi,

I have manually imported several GNPS databases in mgf format, in Metgem 1.2.2
But now when I select some nodes in my project and click on "Find standards in library", an error window is displayed (see details at the end of this message) and no database search is performed. Restarting the application does not solve anything.
The same problem happens when I click on "View databases".

Could you please tell me what has happened and how to solve it ?
Or at least how to erase some user databases that could be the cause of the problem ?

Best regards,

François P

Details : 

Traceback (most recent call last):
  File "site-packages\sqlalchemy\engine\base.py", line 1244, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 552, in do_execute
sqlite3.OperationalError: attempt to write a readonly database

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib\ui\main_window.py", line 912, in <lambda>
  File "lib\logger.py", line 47, in new_func
  File "lib\ui\main_window.py", line 946, in on_query_databases
  File "lib\ui\query_databases_dialog.py", line 41, in __init__
  File "site-packages\sqlalchemy\orm\query.py", line 3317, in __iter__
  File "site-packages\sqlalchemy\orm\query.py", line 3342, in _execute_and_instances
  File "site-packages\sqlalchemy\engine\base.py", line 988, in execute
  File "site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
  File "site-packages\sqlalchemy\engine\base.py", line 1107, in _execute_clauseelement
  File "site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
  File "site-packages\sqlalchemy\engine\base.py", line 1466, in _handle_dbapi_exception
  File "site-packages\sqlalchemy\util\compat.py", line 383, in raise_from_cause
  File "site-packages\sqlalchemy\util\compat.py", line 128, in reraise
  File "site-packages\sqlalchemy\engine\base.py", line 1244, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 552, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database
[SQL: SELECT banks.id AS banks_id, banks.name AS banks_name 
FROM banks]
(Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by n-elie** [comment]
Hi François,

It seems your database is corrupted. You can recover by deleting the database:
In MetGem, go to `Settings > Open user's folder`. This will open an explorer window. Navigate to the `databases` directory and remove everything inside it.
Then, restart MetGem and import your database again.

Also, please consider updating as MetGem 1.2.2 is 3 years old now. You can install [MetGem 1.4.0](https://github.com/metgem/metgem/releases/tag/v1.4.0) that has been released yesterday

**Comment by frperreau** [comment]
Hi Nicolas,

Thank you for your advice which has worked !
I have updated my Metgem version and it is better now.

Have a good weekend.

François

De : Nicolas Elie ***@***.***>
Envoyé : mercredi 18 mai 2022 11:19
À : metgem/metgem ***@***.***>
Cc : Francois Perreau ***@***.***>; Author ***@***.***>
Objet : Re: [metgem/metgem] Database search is down, after manual import of some databases (Issue #106)


Hi François,

It seems your database is corrupted. You can recover by deleting the database:
In MetGem, go to Settings > Open user's folder. This will open an explorer window. Navigate to the databases directory and remove everything inside it.
Then, restart MetGem and import your database again.

Also, please consider updating as MetGem 1.2.2 is 3 years old now. You can install MetGem 1.4.0<https://github.com/metgem/metgem/releases/tag/v1.4.0> that has been released yesterday
