### ISSUE TITLE
Highlight selected node issue

### ISSUE THREAD

**Issue by oolonek** [metgem/metgem#79]
Hi there,
I get the following error when clicking on the "highlight select nodes" option 

```python
Traceback (most recent call last):
  File "lib/logger.py", line 29, in new_func
  File "lib/ui/main_window.py", line 834, in highlight_selected_nodes
  File "lib/ui/widgets/network_view/scene.py", line 125, in setNodesSelection
TypeError: 'set' object does not support indexing
```

**Comment by n-elie** [comment]
Hello,

Could you please test with the newly released 1.1 ?

Regards
