### ISSUE TITLE
MetGem 1.2 Release Candidate 3

### ISSUE THREAD

**Issue by Adafede** [metgem/metgem#82]
Hi, 

When exporting T-SNE graph to cytoscape, no problem. But when trying to export normal network, I get the following error:

```Traceback (most recent call last):
  File "lib/logger.py", line 47, in new_func
  File "lib/ui/main_window.py", line 685, in on_export_to_cytoscape_triggered
  File "site-packages/py2cytoscape/data/network_client.py", line 127, in create_from_igraph
  File "site-packages/py2cytoscape/data/network_client.py", line 106, in create
  File "json/__init__.py", line 231, in dumps
  File "json/encoder.py", line 199, in encode
  File "json/encoder.py", line 257, in iterencode
  File "json/encoder.py", line 179, in default
TypeError: Object of type float32 is not JSON serializable
```

Should you need any more detail don't hesitate

**Comment by n-elie** [comment]
Hi,

Thanks for the report. This was already fixed in development version a few days ago.
Will soon be available in version 1.2.
