### ISSUE TITLE
help for release candidate

### ISSUE THREAD

**Issue by Adafede** [metgem/metgem#85]
Hi,

As last time, maybe this could help you solve the many release candidate trials:

```Traceback (most recent call last):
  File "MetGem", line 4, in <module>
  File "metgem_app/metgem.py", line 64, in run
  File "/usr/local/miniconda/envs/metgem/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "site-packages/sklearn/__init__.py", line 80, in <module>
  File "/usr/local/miniconda/envs/metgem/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "site-packages/sklearn/base.py", line 21, in <module>
  File "/usr/local/miniconda/envs/metgem/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "site-packages/sklearn/utils/__init__.py", line 23, in <module>
  File "/usr/local/miniconda/envs/metgem/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "site-packages/sklearn/utils/class_weight.py", line 7, in <module>
  File "/usr/local/miniconda/envs/metgem/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "site-packages/sklearn/utils/validation.py", line 26, in <module>
  File "/usr/local/miniconda/envs/metgem/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "site-packages/sklearn/utils/fixes.py", line 18, in <module>
  File "/usr/local/miniconda/envs/metgem/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "site-packages/scipy/stats/__init__.py", line 388, in <module>
  File "/usr/local/miniconda/envs/metgem/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "site-packages/scipy/stats/stats.py", line 180, in <module>
  File "/usr/local/miniconda/envs/metgem/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "site-packages/scipy/stats/distributions.py", line 11, in <module>
  File "/usr/local/miniconda/envs/metgem/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "site-packages/scipy/stats/_continuous_distns.py", line 21, in <module>
  File "_stats.pyx", line 1, in init scipy.stats._stats
ModuleNotFoundError: No module named 'scipy.special.cython_special'
[25886] Failed to execute script MetGem
```

Hope this helps, your work is cool!

**Comment by n-elie** [comment]
Hello,

Thanks for your help.
This was fixed in b3fac2a. The next release wil not have this problem.
