### ISSUE TITLE
PHATE "AttributeError: 'dict' object has no attribute 'min_score'"

### ISSUE THREAD

**Issue by simremy** [metgem/metgem#92]
Hello Nicolas, 
Here is a bug report using "Change Network Option"

```
Traceback (most recent call last):
  File "metgem_app\ui\main_window.py", line 1945, in <lambda>
  File "metgem_app\logger.py", line 47, in new_func
  File "metgem_app\ui\main_window.py", line 1742, in on_edit_options_triggered
  File "metgem_app\ui\edit_options_dialog.py", line 25, in __init__
  File "metgem_app\ui\widgets\options_widgets.py", line 227, in setValues
AttributeError: 'dict' object has no attribute 'min_score'
```

Simon

**Comment by n-elie** [comment]
Hello Simon,
I can't reproduce this one. Could you explain with more detail what you did before this error occured?
Nicolas

**Comment by simremy** [comment]
Hi Nicolas,
I generated a PHATE visualization and then click on the change network option button.
Simon
